config/routes.rb
Rails.application.routes.draw do
  resources :archived_bills
  resources :items
  devise_for :users

  resources :bills do
    collection do
      get :index_archive
    end
  end

   root 'bills#index'

end

app/models/bill.rb
class Bill < ActiveRecord::Base
  has_many :items
  belongs_to :user
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]
  before_action :get_current_bill, only: [:index, :create, :charts]

  def index
    @bills = current_user.bills.where.not(archive: true)
    if current_user.bills.count > 0
    @unpaid_items = current_user.bills.first.items.where(paid: 0)
    end
    charts
  end

  def index_archive
    @bills = current_user.bills.where.not(archive: false)
  end


  def show
  end

  def new
    @bill = Bill.new
  end

  def edit
  end

  def create

    if @current_bill
      @current_bill.update_attributes(archive: true)
    end

    @bill = Bill.new(bill_params)
    @bill.user_id = current_user.id
    @bill.archive = false
    respond_to do |format|
      if @bill.save
        format.html { redirect_to new_item_path, notice: 'Bill was successfully created.' }
        format.js   { redirect_to bills_path,  notice: 'Item was successfully Created.' }
      else
        format.html { render :new }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to @bill, notice: 'Bill was successfully updated.' }
        format.json { render :show, status: :ok, location: @bill }
      else
        format.html { render :edit }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to bills_url, notice: 'Bill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def charts

    if @current_bill
    @income = @current_bill.income
    sum     = 0
    @current_bill.items.each { |a| sum+=a.paid }
    @paid = sum
    @left = @income - @paid

    credits = @current_bill.items.where(item_type: 'credit')
    @credit = 0
    credits.each { |a| @credit+=a.paid }

    home_bills = @current_bill.items.where(item_type: 'home')
    @home      = 0
    home_bills.each { |a| @home+=a.paid }

    others = @current_bill.items.where(item_type: 'other')
    @other = 0
    others.each { |a| @other+=a.paid }
   end
    @chart1 = LazyHighCharts::HighChart.new('pie') do |f|
      f.chart({:defaultSeriesType => "pie", :margin => [60, 50, 50, 50]})
      series = {
        :size => '100%',
        :type => 'pie',
        :name => 'Browser share',
        :data => [
          ['income', @income],
          [' total paid', @paid],
          {
            :name => 'total left',
            :y    => @left,

          },
        ]
      }
      f.series(series)
      f.options[:title][:text] = "Metrics"
      f.legend(:layout => 'vertical', :style => {:left => 'auto', :bottom => 'auto', :right => '50px', :top => '50px'})
      f.plot_options(:pie => {
        :allowPointSelect => true,
        :cursor           => "pointer",
        :dataLabels       => {
          :enabled => true,
          :color   => "black",
          :style   => {
            :font => "13px Trebuchet MS, Verdana, sans-serif"
          }
        }
      })
    end

    @chart2 = LazyHighCharts::HighChart.new('pie') do |f|
      f.chart({:defaultSeriesType => "pie"})
      series = {
        :type => 'pie',
        :name => 'Browser share',
        :data => [
          ['total credit', @credit],
          ['total home', @home],
          {
            :name => 'total other',
            :y    => @other,

          },
        ]
      }
      f.series(series)
      f.options[:title][:text] = "Totals"
      f.legend(:layout => 'vertical', :style => {:left => 'auto', :bottom => 'auto', :right => '50px', :top => '50px'})
      f.plot_options(:pie => {
        :allowPointSelect => true,
        :cursor           => "pointer",
        :dataLabels       => {
          :enabled => true,
          :color   => "black",
          :style   => {
            :font => "13px Trebuchet MS, Verdana, sans-serif"
          }
        }
      })
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

  def get_current_bill
    min_id_for_user = current_user.bills.where.not(archive: true).minimum(:id)
    @current_bill = Bill.find(min_id_for_user) unless min_id_for_user.nil?
  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params.require(:bill).permit(:name, :income)
    end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/bills/_form.html.erb
<div id="myModal" >

  <div class="modal-dialog">

    <div class="modal-content">

      <div class="modal-header">

        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>

        <h4 class="modal-title">New/Edit</h4>

      </div>

      <div class="modal-body">


        <%= form_for @bill, :html => { :class => "form-horizontal bill" } do |f| %>

            <div class="control-group">
              <%= f.label :name, :class => 'control-label' %>
              <div class="controls">
                <%= f.text_field :name, :class => 'form-control' %>
              </div>

            </div>

            <div class="control-group">
              <%= f.label :income, :class => 'control-label' %>
              <div class="controls">
                <%= f.text_field :income, :class => 'form-control' %>
              </div>
            </div>

            <div class="modal-footer">

              <%= f.submit nil, :class => 'btn btn-primary' %>
              <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                      bills_path, :class => 'btn btn-default' %>
        <% end %>

        </div>

      </div>

    </div>

  </div>

</div>

app/views/bills/_newbill.html.erb
        Please create a new Bill so we can get started tracking your spending.....

app/views/bills/_results.html.erb
  <div><%= high_chart("my_id4", @chart1) %></div>
  <div><%= high_chart("my_id3", @chart2) %></div>

app/views/bills/edit.html.erb
<%- model_class = Bill -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bills/index.html.erb
<%- model_class = Bill -%>
<div class="bill-table-size">
  <h3><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h3>
    <table class="table table-hover">
      <thead>
        <tr>
          <th><%= model_class.human_attribute_name(:id) %></th>
        </tr>
      </thead>
      <tbody>
        <% @bills.each do |bill| %>
          <tr>
            <td><%= link_to bill.name, items_path(bill, :current_bill => { :bill_id => bill.id }) %></td>
            <td>
              <%= link_to content_tag(
                      :i,
                      nil,
                      class: 'fa fa-pencil fa-lg'
              ),      edit_bill_path(bill) %>

              <%= link_to content_tag(
                      :i,
                      nil,
                      class: 'fa fa-trash-o fa-lg'
              ),      bill_path(bill),
                      :method => :delete,
                      :data   => {:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?'))} %>
            </td>

            <td>
            <% if @unpaid_items.present? %>
                <td><i class="fa fa-times fa-2x"></i></td>
            <% else %>
                <td><i class="fa fa fa-check fa-2x"></i></td>
            <% end %>
            </td>

        <% end %>
      </tr>
      </tbody>
    </table>

          <% if @bills %>
              <%= link_to content_tag(
                      :i,
                      nil,
                      class: 'fa fa-plus-square fa-4x'
              ), new_bill_path, remote: true %>
          <% else %>
              <div id="whatever" class="hidden">
              <%= link_to content_tag(
                      :i,
                      nil,
                      class: 'fa fa-plus-square fa-4x'
              ), new_bill_path, remote: true %>
              </div>
          <% end %>

      <div class="focus-2" id="myModal">
      </div>

  <div class="unpaid-bills">
    <div>
      <h3>Unpaid bills</h3>
      <ul>
        <% unless @unpaid_items.nil? %>
            <% @unpaid_items.each do |bill| %>
                <li><%= bill.item_name %></li>
            <% end %>
        <% end %>
      </ul>
    </div>
  </div>

</div>


<div class="charts-right">
  <%= render partial: 'results' %>
</div>

app/views/bills/index_archive.html.erb
<%- model_class = Bill -%>
<div class="bill-table-size">
  <h3><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h3>
    <table class="table table-hover">
      <thead>
        <tr>
          <th><%= model_class.human_attribute_name(:id) %></th>
        </tr>
      </thead>
      <tbody>
        <% @bills.each do |bill| %>
          <tr>
            <td><%= link_to bill.name, items_path(bill, :current_bill => { :bill_id => bill.id }) %></td>
            <td>
              <%= link_to content_tag(
                      :i,
                      nil,
                      class: 'fa fa-pencil fa-lg'
              ),      edit_bill_path(bill) %>

              <%= link_to content_tag(
                      :i,
                      nil,
                      class: 'fa fa-trash-o fa-lg'
              ),      bill_path(bill),
                      :method => :delete,
                      :data   => {:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?'))} %>
            </td>

            <td>
            <% if @unpaid_items.present? %>
                <td><i class="fa fa-times fa-2x"></i></td>
            <% else %>
                <td><i class="fa fa fa-check fa-2x"></i></td>
            <% end %>
            </td>

        <% end %>
      </tr>
      </tbody>
    </table>
</div>

app/views/bills/new.js.erb
$('#myModal').html("<%= j render("bills/form")%>");
window.location.hash = '#myModal';

app/views/bills/show.html.erb
<%- model_class = Bill -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @bill.name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              bills_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_bill_path(@bill), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              bill_path(@bill),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>