config/routes.rb
Rails.application.routes.draw do
  resources :archived_bills
  resources :items
  devise_for :users

  resources :bills do
    collection do
      get :index_archive
    end
  end

   root 'bills#index'

end

app/models/archived_bill.rb
class ArchivedBill < ActiveRecord::Base
end

app/controllers/archived_bills_controller.rb
class ArchivedBillsController < ApplicationController
  before_action :set_archived_bill, only: [:show, :edit, :update, :destroy]

  # GET /archived_bills
  # GET /archived_bills.json
  def index
    @archived_bills = ArchivedBill.all
  end

  # GET /archived_bills/1
  # GET /archived_bills/1.json
  def show
  end

  # GET /archived_bills/new
  def new
    @archived_bill = ArchivedBill.new
  end

  # GET /archived_bills/1/edit
  def edit
  end

  # POST /archived_bills
  # POST /archived_bills.json
  def create
    @archived_bill = ArchivedBill.new(archived_bill_params)

    respond_to do |format|
      if @archived_bill.save
        format.html { redirect_to @archived_bill, notice: 'Archived bill was successfully created.' }
        format.json { render :show, status: :created, location: @archived_bill }
      else
        format.html { render :new }
        format.json { render json: @archived_bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /archived_bills/1
  # PATCH/PUT /archived_bills/1.json
  def update
    respond_to do |format|
      if @archived_bill.update(archived_bill_params)
        format.html { redirect_to @archived_bill, notice: 'Archived bill was successfully updated.' }
        format.json { render :show, status: :ok, location: @archived_bill }
      else
        format.html { render :edit }
        format.json { render json: @archived_bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /archived_bills/1
  # DELETE /archived_bills/1.json
  def destroy
    @archived_bill.destroy
    respond_to do |format|
      format.html { redirect_to archived_bills_url, notice: 'Archived bill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_archived_bill
      @archived_bill = ArchivedBill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def archived_bill_params
      params.require(:archived_bill).permit(:bill_name, :item_name, :amount, :paid, :sub_total, :item_type)
    end
end

app/helpers/archived_bills_helper.rb
module ArchivedBillsHelper
end

app/views/archived_bills/_form.html.erb
<%= form_for(@archived_bill) do |f| %>
  <% if @archived_bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@archived_bill.errors.count, "error") %> prohibited this archived_bill from being saved:</h2>

      <ul>
      <% @archived_bill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :bill_name %><br>
    <%= f.text_field :bill_name %>
  </div>
  <div class="field">
    <%= f.label :item_name %><br>
    <%= f.text_field :item_name %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </div>
  <div class="field">
    <%= f.label :paid %><br>
    <%= f.number_field :paid %>
  </div>
  <div class="field">
    <%= f.label :sub_total %><br>
    <%= f.number_field :sub_total %>
  </div>
  <div class="field">
    <%= f.label :item_type %><br>
    <%= f.text_field :item_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/archived_bills/edit.html.erb
<h1>Editing Archived Bill</h1>

<%= render 'form' %>

<%= link_to 'Show', @archived_bill %> |
<%= link_to 'Back', archived_bills_path %>

app/views/archived_bills/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Archived Bills</h1>

<table>
  <thead>
    <tr>
      <th>Bill name</th>
      <th>Item name</th>
      <th>Amount</th>
      <th>Paid</th>
      <th>Sub total</th>
      <th>Item type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @archived_bills.each do |archived_bill| %>
      <tr>
        <td><%= archived_bill.bill_name %></td>
        <td><%= archived_bill.item_name %></td>
        <td><%= archived_bill.amount %></td>
        <td><%= archived_bill.paid %></td>
        <td><%= archived_bill.sub_total %></td>
        <td><%= archived_bill.item_type %></td>
        <td><%= link_to 'Show', archived_bill %></td>
        <td><%= link_to 'Edit', edit_archived_bill_path(archived_bill) %></td>
        <td><%= link_to 'Destroy', archived_bill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Archived bill', new_archived_bill_path %>

app/views/archived_bills/new.html.erb
<h1>New Archived Bill</h1>

<%= render 'form' %>

<%= link_to 'Back', archived_bills_path %>

app/views/archived_bills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bill name:</strong>
  <%= @archived_bill.bill_name %>
</p>

<p>
  <strong>Item name:</strong>
  <%= @archived_bill.item_name %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @archived_bill.amount %>
</p>

<p>
  <strong>Paid:</strong>
  <%= @archived_bill.paid %>
</p>

<p>
  <strong>Sub total:</strong>
  <%= @archived_bill.sub_total %>
</p>

<p>
  <strong>Item type:</strong>
  <%= @archived_bill.item_type %>
</p>

<%= link_to 'Edit', edit_archived_bill_path(@archived_bill) %> |
<%= link_to 'Back', archived_bills_path %>