config/routes.rb
Rails.application.routes.draw do
  resources :archived_bills
  resources :items
  devise_for :users

  resources :bills do
    collection do
      get :index_archive
    end
  end

   root 'bills#index'

end

app/views/layouts/_user_widget.html.erb
<% if user_signed_in? %>
    <%= link_to 'Logout', destroy_user_session_path, :method => :delete %>
<% else %>
    <%= link_to 'Login', new_user_session_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BillTrackerApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Bill Tracker</a>
    </div> <!-- end div class="navbar-header" -->
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Browse Products" %></li>
        <li><%= link_to 'Current Bill', bills_path %></li>
        <li><%= link_to 'Older Bills', index_archive_bills_path  %></li>
        <li><%= render 'layouts/user_widget' %></li>
      </ul>
    </div> <!-- end div class="collapse navbar-collapse" -->
  </div> <!-- end div class="container" -->
</div> <!-- end div class="navbar navbar-default navbar-fixed-top" -->

<%= yield %>

</body>
</html>